version: '2.4'

services:

    # nginx
    nginx-service:
        image: nginx:stable-alpine
        container_name: nginx-container
        ports:
            - "8080:80"
        volumes:
            - ./app:/var/www/project
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php74-service
            - mysql8-service

    # php
    php74-service:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: php74-container
        ports:
            - "9000:9000"
        volumes:
            - ./app:/var/www/project

    supervisor:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: supervisor
        volumes:
            - ./app:/var/www/project
            - ./php/conf/supervisord.conf:/etc/supervisor/supervisord.conf
            - ./php/conf/supervisord-programs.conf:/etc/supervisor/conf.d/app.conf
        command: ["supervisord", "-c", "/etc/supervisor/supervisord.conf"]
        depends_on:
            rabbitmq:
                condition: service_healthy

    # mysql
    mysql8-service:
        image: mysql:8
        container_name: mysql8-container
        ports:
            - "4306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
#        restart: always # always restart unless stopped manually
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: mail

    rabbitmq:
        build:
            context: .
            dockerfile: ./rabbitmq/Dockerfile
        ports:
            - "15672:15672"
        environment:
            RABBITMQ_DEFAULT_USER: symfony
            RABBITMQ_DEFAULT_PASS: 12345
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
            interval: 10s
            timeout: 5s
            retries: 10