# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    format_listener:
        rules:
            - { path: '^/',  priorities: [ 'json'], fallback_format: json }
    view:
        view_response_listener:  'force'
        formats:
            json: true
#    param_fetcher_listener:  true
#    allowed_methods_listener:  true
#    routing_loader: true
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
